"""Runtime B Phase 3C-tail — physical pick/place cycle with full telemetry.

This is the *tail* of Phase 3C: physical lift already works, but the peg
slips during transport and the world.reset() does not re-snap the peg
to its authored pose (the dynamic rigid body's runtime state survives
across resets in PhysX). Both blockers are closed here using only
PhysX-supported primitives.

What changed vs Phase 3C (initial)
----------------------------------

1. **Deterministic peg reset.** Every cycle, before play resumes, the
   peg is force-snapped via ``RigidPrim.set_world_poses(authored_xyz,
   authored_orientation)`` and both ``set_linear_velocities`` and
   ``set_angular_velocities`` are zeroed. This is a runtime
   initial-condition write — the same kind already applied to the
   UR10e joints — not a teleport during motion.

2. **Full mimic-chain telemetry.** Every Robotiq 2F-140 sub-joint
   (left/right outer knuckle, outer finger, inner finger, inner pad)
   has its measured position sampled at grasp_close end and at the
   transport mid-point, so the mimic propagation can be verified.

3. **Contact telemetry.** PhysX contact-report events are subscribed
   for the duration of every cycle; counts, peak force magnitude (proxy
   via penetration depth × stiffness scalar), grasp-acquire/-lost
   transitions, and peg↔EE relative transform / slip are reported.

4. **No fake attachment, no parenting, no teleport stabilisation, no
   collision disabling, no runtime IK, no online planning.** The
   only mechanical mechanism holding the peg is friction between the
   Robotiq finger pads and the peg, generated by the joint PD drives.

Cycle timing (slowed in YAML vs Phase 3C-initial to reduce transport
instability; the offline joint-space waypoints are unchanged):

  t=0.0   home @ approach_pick; gripper open; peg on belt
  t=2.0   descended to grasp pose; peg in jaws; gripper begins close
  t=2.5   gripper closed (joint PD has converged)
  t=4.0   peg lifted to z = 0.95            (was 3.3; +0.7 s)
  t=7.5   over approach_place               (was 5.8; +1.5 s relative)
  t=9.5   descended to place pose           (was 7.3)
  t=10.0  gripper open / peg released       (was 7.6)
  t=11.0  retracted above placed peg        (was 8.6)
  t=13.5  back home                          (was 11.1)
"""

from __future__ import annotations

import math
import os
from pathlib import Path

import pytest


try:
    import isaacsim                                       # noqa: F401
    _ISAAC_AVAILABLE = True
except ImportError:
    _ISAAC_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _ISAAC_AVAILABLE,
    reason="Kit Python (Runtime B) required",
)


_WORKSPACE      = Path(__file__).resolve().parents[5]
CELL_STAGE_PATH = _WORKSPACE / "assets" / "cells" / "cell_01.usda"

ROBOT_MOUNT_PATH = "/World/Robot"
BASE_LINK_PATH   = "/World/Robot/base_link"
EE_LINK_PATH     = "/World/Robot/ee_link"
PEG_PATH         = "/World/Parts/Peg_01"
WORK_FIXTURE_PATH= "/World/Environment/WorkFixture"
BELT_COLLIDER_PATH = "/World/Machinery/Conveyor_InFeed/Belt"

PHYSICS_DT_S = 1.0 / 60.0

# Phase 3C-tail tolerance gates.
PEG_PLACE_TOL_XY_M     = 0.05    # peg final XY within 50 mm of place target (sprint contract)
PEG_PLACE_TOL_Z_M      = 0.20
PEG_FALL_THRESHOLD_Z   = 0.30    # peg below this means dropped
CYCLE_DETERMINISM_TOL_M= 5.0e-3  # 5 mm across 3 runs (sprint contract)

PLACE_TARGET_WORLD_M = (0.65, 0.0, 0.65)  # work fixture top center

# Sub-joints driven by the canonical finger_joint via the Robotiq 2F-140
# mimic chain. The articulation API exposes them; we report each so the
# mimic propagation can be eyeballed against the commanded close target.
_GRIPPER_MIMIC_JOINTS = (
    "finger_joint",
    "right_outer_knuckle_joint",
    "left_inner_knuckle_joint",          # Phase 3D: repaired (mimic +1 of finger_joint)
    "right_inner_knuckle_joint",         # Phase 3D: repaired (mimic -1 of finger_joint)
    "left_outer_finger_joint",
    "right_outer_finger_joint",
    "left_inner_finger_joint",
    "right_inner_finger_joint",
    "left_inner_finger_pad_joint",
    "right_inner_finger_pad_joint",
)


@pytest.fixture(scope="module")
def sim_app():
    from isaacsim import SimulationApp
    app = SimulationApp({"headless": True})
    yield app
    app.close()


@pytest.fixture
def cell_stage(sim_app):
    import omni.usd
    ctx = omni.usd.get_context()
    assert CELL_STAGE_PATH.is_file(), f"missing stage: {CELL_STAGE_PATH}"
    r = ctx.open_stage(str(CELL_STAGE_PATH))
    ok = bool(r[0]) if isinstance(r, tuple) else bool(r)
    assert ok
    yield ctx.get_stage()


@pytest.fixture
def world(cell_stage):
    from isaacsim.core.api import World
    w = World(physics_dt=PHYSICS_DT_S, rendering_dt=PHYSICS_DT_S)
    w.reset()
    w.play()
    yield w
    w.clear_instance()


# ============================================================ helpers ==


def _load_cfg():
    import sys
    sys.path.insert(0, str(_WORKSPACE / "isaac_factory" / "extensions" / "cell_authoring"))
    from cell_authoring import load_config
    return load_config(_WORKSPACE / "configs" / "cell_01.yaml")


def _make_player(stage, cfg):
    """Construct a TrajectoryPlayer.

    Honours ``PHASE_3C_CLOSE_RAD`` env var when set: rewrites
    ``cfg.robot.gripper.close_position_rad`` on the in-memory config so
    the sweep over {0.50, 0.55, 0.60, 0.65} can be driven without
    re-editing the YAML or rebuilding the cell stage. The close target
    is consumed at runtime by ``TrajectoryPlayer._write_gripper_command``
    only, so no stage rebuild is required.
    """
    import sys
    import dataclasses
    sys.path.insert(0, str(_WORKSPACE / "isaac_factory" / "extensions" / "cell_authoring"))
    from cell_authoring.trajectory import TrajectoryPlayer

    override = os.environ.get("PHASE_3C_CLOSE_RAD")
    if override is not None:
        try:
            override_v = float(override)
            new_grip = dataclasses.replace(cfg.robot.gripper, close_position_rad=override_v)
            new_robot = dataclasses.replace(cfg.robot, gripper=new_grip)
            cfg = dataclasses.replace(cfg, robot=new_robot)
            print(f"[phase_3c_tail] PHASE_3C_CLOSE_RAD={override_v} (overrides YAML)")
        except (ValueError, TypeError):
            pass
    return TrajectoryPlayer(stage=stage, robot_cfg=cfg.robot), cfg


def _world_transform(stage, path: str):
    """Return (translate_xyz, 3x3 rotation matrix as nested tuple)."""
    from pxr import UsdGeom, Usd, Gf
    prim = stage.GetPrimAtPath(path)
    mat = UsdGeom.Xformable(prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default())
    mat = mat.RemoveScaleShear()
    t = mat.ExtractTranslation()
    r = mat.ExtractRotation().GetQuat()
    rot33 = Gf.Matrix3d(mat.ExtractRotationMatrix())
    rot = tuple(tuple(float(rot33[i][j]) for j in range(3)) for i in range(3))
    return (float(t[0]), float(t[1]), float(t[2])), rot, (
        float(r.GetReal()),
        float(r.GetImaginary()[0]),
        float(r.GetImaginary()[1]),
        float(r.GetImaginary()[2]),
    )


def _world_translate(stage, path: str) -> tuple[float, float, float]:
    t, _, _ = _world_transform(stage, path)
    return t


def _relative_translate(parent_t, parent_rot33, child_t):
    """Express child_t in the parent frame: rot^T * (child - parent)."""
    dx = child_t[0] - parent_t[0]
    dy = child_t[1] - parent_t[1]
    dz = child_t[2] - parent_t[2]
    # rot33 columns are world axes of the parent's frame; rot33^T * delta.
    rx = parent_rot33[0][0]*dx + parent_rot33[1][0]*dy + parent_rot33[2][0]*dz
    ry = parent_rot33[0][1]*dx + parent_rot33[1][1]*dy + parent_rot33[2][1]*dz
    rz = parent_rot33[0][2]*dx + parent_rot33[1][2]*dy + parent_rot33[2][2]*dz
    return (rx, ry, rz)


_UR10E_JOINT_NAMES = (
    "shoulder_pan", "shoulder_lift", "elbow",
    "wrist_1", "wrist_2", "wrist_3",
)


def _build_articulation(world):
    """Initialise the UR10e articulation handle once per test.

    Phase 3I: pass the Xform path (``/World/Robot``) not the joint path.
    The working ``test_articulation_view.py`` examples initialise
    ``Articulation(prim_paths_expr="/World/Franka_[1-2]")`` — the
    articulation root Xform glob, not its child joint. Adding to
    ``world.scene`` is also part of the canonical Isaac Sim flow that
    binds the articulation to the world's physics view.
    """
    import json
    from isaacsim.core.prims import Articulation
    art = Articulation(prim_paths_expr=ROBOT_MOUNT_PATH)
    try:
        world.scene.add(art)
    except Exception:                                               # noqa: BLE001
        pass
    art.initialize()
    # Phase 3E debug: persist DOF list to a sidecar file (pytest captures
    # stdout, so a print would be invisible).
    try:
        dof_dump = {
            "dof_names": list(art.dof_names),
            "num_dof":   len(art.dof_names),
        }
        Path(_TELEMETRY_JSONL).parent.mkdir(parents=True, exist_ok=True)
        with open(str(Path(_TELEMETRY_JSONL).parent / "phase_3e_dof_dump.json"), "w") as fh:
            json.dump(dof_dump, fh, indent=2)
    except Exception:                                               # noqa: BLE001
        pass
    joint_indices = [
        list(art.dof_names).index(f"{n}_joint") for n in _UR10E_JOINT_NAMES
    ]
    return art, joint_indices


def _build_peg_rigid(world):
    """Return a runtime RigidPrim handle for the peg.

    Used to set_world_poses + zero velocities at cycle reset — this is
    the determinism fix for Phase 3C-tail. Without it, the peg's runtime
    pose / velocity carries over across ``World.reset()`` (PhysX preserves
    dynamic-body state until something else writes it).
    """
    from isaacsim.core.prims import RigidPrim
    peg = RigidPrim(prim_paths_expr=PEG_PATH)
    peg.initialize()
    return peg


def _reset_peg_to_authored(peg, cfg):
    """Snap peg to authored world pose, zero linear + angular velocities.

    No fake attachment, no parenting, no teleport mid-trajectory — this
    is an initial-condition write at t=0 only (sprint contract: "runtime
    initial-condition write is permitted; trajectory-time teleport is
    not").
    """
    import numpy as np

    authored_xyz = cfg.parts[0].translate_world_m
    positions = np.array([[authored_xyz[0], authored_xyz[1], authored_xyz[2]]],
                         dtype=np.float32)
    # Identity quaternion (w, x, y, z) — peg authored without rotation.
    orientations = np.array([[1.0, 0.0, 0.0, 0.0]], dtype=np.float32)
    peg.set_world_poses(positions=positions, orientations=orientations)
    peg.set_linear_velocities(np.zeros((1, 3), dtype=np.float32))
    peg.set_angular_velocities(np.zeros((1, 3), dtype=np.float32))


def _gripper_mimic_joint_indices(articulation):
    """Map each known mimic sub-joint name to its DOF index (or None)."""
    out: dict[str, int | None] = {}
    for n in _GRIPPER_MIMIC_JOINTS:
        try:
            out[n] = list(articulation.dof_names).index(n)
        except ValueError:
            out[n] = None
    return out


def _run_full_cycle(world, stage, player, articulation, joint_indices,
                    peg, cfg, *, cycle_index: int = 0,
                    contact_source=None) -> dict:
    """Execute one full cycle and gather telemetry.

    Returns a dict with deterministic keys (see telemetry summary below).
    """
    import numpy as np

    world.reset()
    world.play()                # ensure physics view is active after reset
    player.reset()

    # Phase 3H v11: re-initialize the articulation handle AFTER
    # world.play() so the freshly-created PhysicsSimulationView is
    # what the Articulation binds to.
    try:
        articulation.initialize()
    except Exception:                                               # noqa: BLE001
        pass

    # ------------------------- arm initial joint state ----------------
    home_pose = dict(player._cfg.home_pose_rad)
    full = articulation.get_joint_positions()
    for i, name in enumerate(_UR10E_JOINT_NAMES):
        full[0][joint_indices[i]] = float(home_pose[name])
    articulation.set_joint_positions(full)
    articulation.set_joint_position_targets(full)

    # ------------------------- peg deterministic reset ----------------
    # Snap peg to authored world pose + zero velocities. This is the
    # Phase 3C-tail determinism fix: World.reset() does not re-snap a
    # dynamic rigid body whose runtime state was perturbed by a prior
    # cycle (it preserves PhysX-internal state). We explicitly write the
    # authored initial condition before play resumes.
    _reset_peg_to_authored(peg, cfg)

    # Settle for a few steps so the gripper / floating link state is
    # consistent before the trajectory begins.
    for _ in range(10):
        world.step(render=False)
    # Re-assert peg pose after settle — otherwise the small gravity tick
    # during settle perturbs it before t=0 of the trajectory.
    _reset_peg_to_authored(peg, cfg)

    # Drain any contact captured during the settle window — those don't
    # belong to the measurement.
    if contact_source is not None:
        contact_source.query_contacts()

    # ------------------------- indexed-belt control ------------------
    # Phase 3E: halt the belt during the grasp window so the peg does
    # not slip out of the fingers during the close. This is a pure-PhysX
    # surface-velocity write — the belt remains a kinematic rigid body
    # the whole time, the peg is still held by the same friction model
    # (no fake attachment, no parenting, no teleport). The belt's
    # ``physxSurfaceVelocity:surfaceVelocity`` attribute is the same
    # one PhysX is already reading every step to drive belt friction;
    # setting it to (0,0,0) is equivalent to a real conveyor being
    # paused by its motor controller.
    belt_attr = stage.GetAttributeAtPath(BELT_COLLIDER_PATH + ".physxSurfaceVelocity:surfaceVelocity")
    original_belt_v = None
    if belt_attr is not None and belt_attr.IsValid():
        from pxr import Gf
        original_belt_v = belt_attr.Get()
        if original_belt_v is None:
            original_belt_v = Gf.Vec3f(0.0, 0.0, 0.0)

    def _set_belt_velocity(vec):
        if belt_attr is not None and belt_attr.IsValid():
            from pxr import Gf
            belt_attr.Set(Gf.Vec3f(float(vec[0]), float(vec[1]), float(vec[2])))

    # Ensure the belt is at its authored speed at the start of every
    # cycle (the previous cycle may have left it halted).
    if original_belt_v is not None:
        _set_belt_velocity(original_belt_v)

    # ------------------------- timing landmarks -----------------------
    waypoints = list(player._cfg.trajectory)
    cumulative = []
    t = 0.0
    for wp in waypoints:
        t += wp.duration_s
        cumulative.append(t)
    name_to_end_t = {wp.name: cumulative[i] for i, wp in enumerate(waypoints)}

    grasp_close_end_s = name_to_end_t.get("grasp_close", 2.5)
    lift_end_s        = name_to_end_t.get("lift",        grasp_close_end_s + 1.5)
    place_end_s       = name_to_end_t.get("place",       lift_end_s + 3.5)
    release_end_s     = name_to_end_t.get("release",     place_end_s + 0.5)
    total_s           = cumulative[-1]

    grasp_close_step = int(round(grasp_close_end_s / PHYSICS_DT_S))
    lift_end_step    = int(round(lift_end_s        / PHYSICS_DT_S))
    place_end_step   = int(round(place_end_s       / PHYSICS_DT_S))
    release_end_step = int(round(release_end_s     / PHYSICS_DT_S))
    n_steps          = int(round(total_s           / PHYSICS_DT_S)) + 60

    # Indexed-belt halt range: freeze the belt the moment the gripper
    # reaches grasp pose (end of the "grasp" waypoint, NOT the start of
    # close — see Phase 3E v3 calibration). The 0.5 s close window is
    # then run with a stationary peg, so PD has full settling time
    # without slip. Belt restarts at lift_end so the next peg can
    # advance — though this cycle does not feed a second peg.
    grasp_pose_reached_s = name_to_end_t.get("grasp", grasp_close_end_s - 0.5)
    belt_halt_start_step = int(round(grasp_pose_reached_s / PHYSICS_DT_S))
    belt_halt_end_step   = int(round((lift_end_s)         / PHYSICS_DT_S))

    # ------------------------- DOF index resolution -------------------
    grip_idx = None
    right_grip_idx = None
    for i, n in enumerate(articulation.dof_names):
        if n == player._cfg.gripper.drive_joint_name:
            grip_idx = i
        if n == "right_finger_joint":
            right_grip_idx = i
    mimic_idx = _gripper_mimic_joint_indices(articulation)

    # ------------------------- telemetry buffer -----------------------
    telemetry: dict = {
        "cycle_index":              cycle_index,
        "close_position_rad":       float(player._cfg.gripper.close_position_rad),
        "min_peg_z_world":          1e9,
        "max_peg_z_world":         -1e9,
        "peg_xyz_initial":          None,
        "peg_xyz_at_grasp_close":   None,
        "peg_xyz_at_lift_end":      None,
        "peg_xyz_at_place":         None,
        "peg_xyz_final":            None,
        "peg_in_ee_at_close":       None,
        "peg_in_ee_max_slip_mm":    0.0,
        "peg_in_ee_final_slip_mm":  None,
        "mimic_joint_pos_at_close": {},
        "mimic_joint_pos_at_lift":  {},
        "pad_separation_min_m":     1e9,
        "contact_count_total":      0,
        "contact_count_peak":       0,
        "max_penetration_m":        0.0,
        "grasp_acquired_step":      None,
        "grasp_lost_step":          None,
        "peg_drop_step":            None,
    }

    telemetry["peg_xyz_initial"] = _world_translate(stage, PEG_PATH)
    peg_in_ee_at_close: tuple[float, float, float] | None = None

    in_grasp = False  # state machine for acquire/lost detection

    import numpy as np
    import math as _math
    _DEG2RAD = _math.pi / 180.0

    for step_i in range(n_steps):
        # --- write joint + gripper targets ------------------------
        # Phase 3I: the USD drive attribute holds the target in DEGREES
        # (per the UsdPhysics spec — Isaac Sim runtime API requires
        # RADIANS). Convert when forwarding to the articulation API.
        full_target = np.array(articulation.get_joint_positions(), dtype=np.float32).copy()
        for i, name in enumerate(_UR10E_JOINT_NAMES):
            attr_path = (
                f"{player._cfg.mount_prim_path}/joints/{name}_joint"
                f".drive:angular:physics:targetPosition"
            )
            attr = stage.GetAttributeAtPath(attr_path)
            if attr and attr.IsValid():
                full_target[0, joint_indices[i]] = float(attr.Get()) * _DEG2RAD
        if grip_idx is not None and player._gripper_attr_path is not None:
            gattr = stage.GetAttributeAtPath(player._gripper_attr_path)
            if gattr and gattr.IsValid():
                # Phase 3K: scale only for angular (revolute) gripper drives.
                # For prismatic, the target is already in metres — applying
                # _DEG2RAD scales it by π/180 ≈ 0.0175, which silently
                # turned the 30 mm close stroke into a 0.5 mm one.
                grip_scale = _DEG2RAD if getattr(player, "_gripper_drive_is_angular", True) else 1.0
                target_v = float(gattr.Get()) * grip_scale
                full_target[0, grip_idx] = target_v
                # Phase 3K v5: also drive the mimic-follower right_finger_joint
                # explicitly. PhysxMimicJointAPI didn't propagate the close
                # to the right pad when its own drive stiffness was zero
                # (right pad stayed at ±0.045 while left pad moved to 0.015).
                # Writing the mirrored target via the articulation API
                # guarantees symmetric closure regardless of mimic behaviour.
                if right_grip_idx is not None and not getattr(player, "_gripper_drive_is_angular", True):
                    full_target[0, right_grip_idx] = -target_v
        articulation.set_joint_position_targets(full_target)

        # Phase 3E indexed-belt halt: zero the belt surfaceVelocity for
        # the close+lift window so the peg does not slip out of the
        # gripper during the brief close phase. Restored at lift_end.
        if step_i == belt_halt_start_step:
            _set_belt_velocity((0.0, 0.0, 0.0))
        elif step_i == belt_halt_end_step and original_belt_v is not None:
            _set_belt_velocity(original_belt_v)

        world.step(render=False)
        player.advance(PHYSICS_DT_S)

        peg_xyz = _world_translate(stage, PEG_PATH)
        telemetry["min_peg_z_world"] = min(telemetry["min_peg_z_world"], peg_xyz[2])
        telemetry["max_peg_z_world"] = max(telemetry["max_peg_z_world"], peg_xyz[2])

        # Phase 3D peg-trajectory probe — once per 6 steps (~100 ms) so
        # we can resolve when the peg actually leaves the gripper.
        if cycle_index == 0 and step_i % 6 == 0:
            telemetry.setdefault("peg_traj", []).append(
                (step_i, peg_xyz[0], peg_xyz[1], peg_xyz[2])
            )
        # Phase 3H: trace shoulder_lift position + applied target every
        # 30 steps. If get_applied_actions().joint_positions[1] doesn't
        # match what we wrote in set_joint_position_targets, the API
        # isn't honouring our calls.
        if cycle_index == 0 and step_i % 30 == 0:
            try:
                cur = articulation.get_joint_positions()
                shoulder_lift_idx = joint_indices[1]
                applied_action = articulation.get_applied_actions()
                applied_pos = (float(applied_action.joint_positions[0][shoulder_lift_idx])
                               if applied_action.joint_positions is not None else None)
                # Also read what the USD attribute currently says.
                usd_target_attr = stage.GetAttributeAtPath(
                    f"{player._cfg.mount_prim_path}/joints/shoulder_lift_joint"
                    f".drive:angular:physics:targetPosition"
                )
                usd_target = float(usd_target_attr.Get()) if usd_target_attr else None
                telemetry.setdefault("shoulder_lift_traj", []).append(
                    (step_i, float(cur[0][shoulder_lift_idx]), applied_pos, usd_target)
                )
            except Exception as e:                                  # noqa: BLE001
                telemetry.setdefault("shoulder_lift_traj_error", []).append(str(e))
            # Phase 3E: also capture left_finger world position so we can
            # verify whether the gripper is actually rising during the
            # lift phase. /World/Robot/ee_link's USD transform is NOT
            # synced from PhysX every step (Isaac Sim writes the world
            # pose only on certain triggers), so we read the FINGER
            # instead — it's a dynamic rigid body, so PhysX keeps its
            # USD xform fresh every step.
            try:
                lfin = _world_translate(stage, "/World/Robot/ee_link/left_inner_finger")
                telemetry.setdefault("left_finger_traj", []).append(
                    (step_i, lfin[0], lfin[1], lfin[2])
                )
            except Exception:                                      # noqa: BLE001
                pass

        # First-fall detection.
        if telemetry["peg_drop_step"] is None and peg_xyz[2] < PEG_FALL_THRESHOLD_Z and step_i > grasp_close_step:
            telemetry["peg_drop_step"] = step_i

        # ---- per-phase snapshots ------------------------------------
        if step_i == grasp_close_step:
            telemetry["peg_xyz_at_grasp_close"] = peg_xyz
            ee_t, ee_rot, _ = _world_transform(stage, EE_LINK_PATH)
            peg_in_ee_at_close = _relative_translate(ee_t, ee_rot, peg_xyz)
            telemetry["peg_in_ee_at_close"] = peg_in_ee_at_close
            # Phase 3H: dump ALL joint positions AND commanded targets
            # so we can see whether (a) the trajectory player is writing
            # the right targets to the USD attributes, and (b) the
            # articulation is actually tracking those targets.
            try:
                cur = articulation.get_joint_positions()
                telemetry["all_joint_pos_at_close"] = [
                    (n, float(cur[0][i])) for i, n in enumerate(articulation.dof_names)
                ]
                # Phase 3K v6: also dump the APPLIED targets for both
                # gripper joints to see whether the explicit API write
                # actually reaches PhysX.
                aa = articulation.get_applied_actions()
                if aa is not None and aa.joint_positions is not None:
                    telemetry["applied_targets_at_close"] = [
                        (n, float(aa.joint_positions[0][i]))
                        for i, n in enumerate(articulation.dof_names)
                    ]
            except Exception:                                       # noqa: BLE001
                pass
            try:
                tgt = []
                for name in _UR10E_JOINT_NAMES:
                    attr = stage.GetAttributeAtPath(
                        f"{player._cfg.mount_prim_path}/joints/{name}_joint"
                        f".drive:angular:physics:targetPosition"
                    )
                    if attr and attr.IsValid():
                        tgt.append((name, float(attr.Get())))
                telemetry["arm_joint_target_at_close"] = tgt
            except Exception:                                       # noqa: BLE001
                pass
            # Phase 3G: read finger world positions via RigidPrim (USD's
            # local-to-world transform doesn't sync with PhysX for
            # articulation links during simulation). Try both legacy
            # 2F-140 names and the Phase 3G arm names.
            try:
                from isaacsim.core.prims import RigidPrim
                # Phase 3H: probe wrist_3_link and robotiq_base_link too so
                # we can see whether the articulation propagates ACROSS
                # ee_joint. If wrist_3 moves to approach_pick but
                # robotiq_base_link stays at default, the joint isn't
                # cooked into the articulation.
                probe_paths = (
                    ("wrist_3_link_at_close",       "/World/Robot/wrist_3_link"),
                    ("robotiq_base_at_close",       "/World/Robot/ee_link/robotiq_base_link"),
                    ("left_finger_at_close",        "/World/Robot/ee_link/left_finger"),
                    ("right_finger_at_close",       "/World/Robot/ee_link/right_finger"),
                )
                for tag, path in probe_paths:
                    try:
                        rp = RigidPrim(prim_paths_expr=path)
                        rp.initialize()
                        pos, _ = rp.get_world_poses()
                        telemetry[tag] = (float(pos[0][0]), float(pos[0][1]), float(pos[0][2]))
                    except Exception:                              # noqa: BLE001
                        pass
            except Exception:                                       # noqa: BLE001
                pass

            cur = articulation.get_joint_positions()
            telemetry["mimic_joint_pos_at_close"] = {
                n: (float(cur[0][i]) if i is not None else None)
                for n, i in mimic_idx.items()
            }
            # pad separation: distance between left + right inner finger
            # pads. We use the body translates from USD as a proxy.
            try:
                ltip = _world_translate(stage, "/World/Robot/ee_link/left_inner_finger/Fingertip_01")
                rtip = _world_translate(stage, "/World/Robot/ee_link/right_inner_finger/Fingertip_01")
                sep = math.sqrt(sum((a - b) ** 2 for a, b in zip(ltip, rtip)))
                telemetry["pad_separation_min_m"] = min(telemetry["pad_separation_min_m"], sep)
            except Exception:                                       # noqa: BLE001
                pass

        if step_i == lift_end_step:
            telemetry["peg_xyz_at_lift_end"] = peg_xyz
            try:
                cur = articulation.get_joint_positions()
                telemetry["all_joint_pos_at_lift"] = [
                    (n, float(cur[0][i])) for i, n in enumerate(articulation.dof_names)
                ]
            except Exception:                                       # noqa: BLE001
                pass
            cur = articulation.get_joint_positions()
            telemetry["mimic_joint_pos_at_lift"] = {
                n: (float(cur[0][i]) if i is not None else None)
                for n, i in mimic_idx.items()
            }

        if step_i == place_end_step:
            telemetry["peg_xyz_at_place"] = peg_xyz

        # ---- slip tracking ------------------------------------------
        if peg_in_ee_at_close is not None and step_i >= grasp_close_step:
            ee_t, ee_rot, _ = _world_transform(stage, EE_LINK_PATH)
            peg_in_ee_now = _relative_translate(ee_t, ee_rot, peg_xyz)
            slip_mm = 1000.0 * math.sqrt(
                sum((a - b) ** 2 for a, b in zip(peg_in_ee_now, peg_in_ee_at_close))
            )
            telemetry["peg_in_ee_max_slip_mm"] = max(telemetry["peg_in_ee_max_slip_mm"], slip_mm)
            # Sampled at end of transport for the final report.
            if step_i == place_end_step:
                telemetry["peg_in_ee_final_slip_mm"] = slip_mm

            # ---- pad separation (running min during grasp/transport)
            try:
                ltip = _world_translate(stage, "/World/Robot/ee_link/left_inner_finger/Fingertip_01")
                rtip = _world_translate(stage, "/World/Robot/ee_link/right_inner_finger/Fingertip_01")
                sep = math.sqrt(sum((a - b) ** 2 for a, b in zip(ltip, rtip)))
                if step_i <= release_end_step:
                    telemetry["pad_separation_min_m"] = min(telemetry["pad_separation_min_m"], sep)
            except Exception:                                       # noqa: BLE001
                pass

            # ---- grasp acquire/lost state machine -------------------
            # "grasp acquired" := peg z > authored_z + 5 mm after grasp_close
            # "grasp lost"     := after acquired, peg z < authored_z - 10 mm
            authored_z = cfg.parts[0].translate_world_m[2]
            if not in_grasp and peg_xyz[2] > authored_z + 0.005 and step_i > grasp_close_step:
                in_grasp = True
                if telemetry["grasp_acquired_step"] is None:
                    telemetry["grasp_acquired_step"] = step_i
            elif in_grasp and peg_xyz[2] < authored_z - 0.010 and step_i < release_end_step - 30:
                in_grasp = False
                if telemetry["grasp_lost_step"] is None:
                    telemetry["grasp_lost_step"] = step_i

        # ---- contact accumulation -----------------------------------
        if contact_source is not None:
            contacts = contact_source.query_contacts()
            telemetry["contact_count_total"] += len(contacts)
            telemetry["contact_count_peak"]   = max(
                telemetry["contact_count_peak"], len(contacts),
            )
            for c in contacts:
                telemetry["max_penetration_m"] = max(
                    telemetry["max_penetration_m"], float(c.penetration_depth),
                )

    telemetry["peg_xyz_final"] = _world_translate(stage, PEG_PATH)
    return telemetry


_TELEMETRY_JSONL = os.environ.get(
    "PHASE_3C_TELEMETRY_JSONL",
    str(_WORKSPACE / "logs" / "phase_3c_tail_telemetry.jsonl"),
)


def _print_telemetry(tel: dict) -> None:
    """Human-readable telemetry dump + JSONL sidecar (survives pytest capture)."""
    import json
    keys = (
        "cycle_index", "close_position_rad",
        "peg_xyz_initial", "peg_xyz_at_grasp_close",
        "peg_xyz_at_lift_end", "peg_xyz_at_place", "peg_xyz_final",
        "min_peg_z_world", "max_peg_z_world",
        "peg_in_ee_at_close", "peg_in_ee_max_slip_mm", "peg_in_ee_final_slip_mm",
        "pad_separation_min_m",
        "contact_count_total", "contact_count_peak", "max_penetration_m",
        "grasp_acquired_step", "grasp_lost_step", "peg_drop_step",
    )
    print(f"\n[telemetry cycle={tel['cycle_index']}]")
    for k in keys:
        print(f"    {k}: {tel[k]}")
    print(f"    mimic_joint_pos_at_close:")
    for n, v in tel["mimic_joint_pos_at_close"].items():
        print(f"        {n}: {v}")
    print(f"    mimic_joint_pos_at_lift:")
    for n, v in tel["mimic_joint_pos_at_lift"].items():
        print(f"        {n}: {v}")
    # Persist to JSONL so pytest's stdout capture cannot hide it.
    try:
        Path(_TELEMETRY_JSONL).parent.mkdir(parents=True, exist_ok=True)
        with open(_TELEMETRY_JSONL, "a") as fh:
            fh.write(json.dumps(tel, default=str) + "\n")
    except Exception:                                               # noqa: BLE001
        pass


# ============================================================ pre-flight ==


class TestPreflight:
    def test_stage_loads_with_robot_and_gripper(self, cell_stage):
        from pxr import UsdPhysics, Usd
        n_art_roots = sum(
            1 for p in Usd.PrimRange.Stage(cell_stage, Usd.TraverseInstanceProxies())
            if p.HasAPI(UsdPhysics.ArticulationRootAPI)
        )
        assert n_art_roots >= 1, "no articulation root composed"

    def test_peg_starts_at_configured_position(self, cell_stage):
        cfg = _load_cfg()
        peg = _world_translate(cell_stage, PEG_PATH)
        target = cfg.parts[0].translate_world_m
        for ax, (a, b) in enumerate(zip(peg, target)):
            assert abs(a - b) < 1.0e-3, f"axis {ax}: actual={a} config={b}"


# ============================================================ cycle ==


def _make_contact_source(stage):
    """Best-effort contact-source construction.

    Returns ``None`` if omni.physx isn't in the environment (tests still
    run; contact telemetry is just zeroed).
    """
    try:
        import sys
        sys.path.insert(0, str(_WORKSPACE / "isaac_factory" / "extensions" / "asset_validator"))
        from asset_validator.adapters.physx_contact_source import PhysXContactSource
        return PhysXContactSource(stage=stage, physics_dt=PHYSICS_DT_S)
    except Exception as e:                                          # noqa: BLE001
        print(f"[telemetry] contact source disabled: {type(e).__name__}: {e}")
        return None


class TestCycleTelemetry:
    """Phase 3C-tail: actual physical transfer with full telemetry."""

    def test_peg_was_lifted_during_cycle(self, world, cell_stage):
        cfg    = _load_cfg()
        player, cfg = _make_player(cell_stage, cfg)
        art,ji = _build_articulation(world)
        peg    = _build_peg_rigid(world)
        cs     = _make_contact_source(cell_stage)
        try:
            tel = _run_full_cycle(world, cell_stage, player, art, ji,
                                  peg, cfg, cycle_index=0, contact_source=cs)
        finally:
            if cs is not None:
                cs.close()
        _print_telemetry(tel)
        peg_rest_z = cfg.parts[0].translate_world_m[2]
        assert tel["max_peg_z_world"] > peg_rest_z + 0.02, (
            f"peg never lifted above {peg_rest_z + 0.02:.3f}; "
            f"max_peg_z = {tel['max_peg_z_world']:.4f}"
        )

    def test_peg_did_not_drop_to_floor(self, world, cell_stage):
        cfg    = _load_cfg()
        player, cfg = _make_player(cell_stage, cfg)
        art,ji = _build_articulation(world)
        peg    = _build_peg_rigid(world)
        cs     = _make_contact_source(cell_stage)
        try:
            tel = _run_full_cycle(world, cell_stage, player, art, ji,
                                  peg, cfg, cycle_index=0, contact_source=cs)
        finally:
            if cs is not None:
                cs.close()
        _print_telemetry(tel)
        assert tel["min_peg_z_world"] > PEG_FALL_THRESHOLD_Z, (
            f"peg fell to floor: min_z = {tel['min_peg_z_world']:.4f}, "
            f"threshold = {PEG_FALL_THRESHOLD_Z}"
        )

    def test_peg_ended_near_place_target_xy(self, world, cell_stage):
        cfg    = _load_cfg()
        player, cfg = _make_player(cell_stage, cfg)
        art,ji = _build_articulation(world)
        peg    = _build_peg_rigid(world)
        cs     = _make_contact_source(cell_stage)
        try:
            tel = _run_full_cycle(world, cell_stage, player, art, ji,
                                  peg, cfg, cycle_index=0, contact_source=cs)
        finally:
            if cs is not None:
                cs.close()
        _print_telemetry(tel)
        peg_f = tel["peg_xyz_final"]
        dx = abs(peg_f[0] - PLACE_TARGET_WORLD_M[0])
        dy = abs(peg_f[1] - PLACE_TARGET_WORLD_M[1])
        assert dx < PEG_PLACE_TOL_XY_M, (
            f"peg.x = {peg_f[0]:.4f}, place target = {PLACE_TARGET_WORLD_M[0]:.4f}, "
            f"|dx| = {dx:.4f} (tol {PEG_PLACE_TOL_XY_M})"
        )
        assert dy < PEG_PLACE_TOL_XY_M, (
            f"peg.y = {peg_f[1]:.4f}, |dy| = {dy:.4f} (tol {PEG_PLACE_TOL_XY_M})"
        )


# ============================================================ determinism ==


class TestThreeCycleDeterminism:
    """3 full cycles → same peg final pose within 5 mm.

    Each cycle force-resets the peg's runtime pose + velocities via
    RigidPrim.set_world_poses + set_*_velocities. This is the
    Phase 3C-tail determinism fix.
    """

    def test_three_cycles_match(self, world, cell_stage):
        cfg    = _load_cfg()
        player, cfg = _make_player(cell_stage, cfg)
        art,ji = _build_articulation(world)
        peg    = _build_peg_rigid(world)
        cs     = _make_contact_source(cell_stage)
        snaps: list[tuple[float, float, float]] = []
        try:
            for i in range(3):
                tel = _run_full_cycle(
                    world, cell_stage, player, art, ji,
                    peg, cfg, cycle_index=i, contact_source=cs,
                )
                _print_telemetry(tel)
                snaps.append(tel["peg_xyz_final"])
        finally:
            if cs is not None:
                cs.close()

        # Determinism check: cycle 1, 2 vs cycle 0.
        for k in (1, 2):
            for ax, (a, b) in enumerate(zip(snaps[0], snaps[k])):
                delta = abs(a - b)
                assert delta < CYCLE_DETERMINISM_TOL_M, (
                    f"non-deterministic: peg axis {ax} "
                    f"cycle0={a:.6f} cycle{k}={b:.6f} delta={delta:.6f}"
                )
